from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settings_window(object):
	def setupUi(self, settings_window):
		settings_window.setObjectName("settings_window")
		settings_window.resize(558, 460)
		settings_window.setStyleSheet("background-color: rgb(255, 255, 255);")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("Bin/Icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		settings_window.setWindowIcon(icon)
		settings_window.setMaximumSize(QtCore.QSize(558, 460))
		settings_window.setMinimumSize(QtCore.QSize(558, 460))
		settings_window.setWindowFlags(settings_window.windowFlags() & QtCore.Qt.CustomizeWindowHint)
		settings_window.setWindowFlags(settings_window.windowFlags() & ~QtCore.Qt.WindowMinMaxButtonsHint)
		self.centralwidget = QtWidgets.QWidget(settings_window)
		self.centralwidget.setObjectName("centralwidget")
		self.tabs_ = QtWidgets.QTabWidget(self.centralwidget)
		self.tabs_.setGeometry(QtCore.QRect(0, 0, 561, 461))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(13)
		self.tabs_.setFont(font)
		self.tabs_.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.tabs_.setTabPosition(QtWidgets.QTabWidget.West)
		self.tabs_.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.tabs_.setElideMode(QtCore.Qt.ElideNone)
		self.tabs_.setUsesScrollButtons(True)
		self.tabs_.setDocumentMode(False)
		self.tabs_.setTabsClosable(False)
		self.tabs_.setMovable(False)
		self.tabs_.setTabBarAutoHide(False)
		self.tabs_.setObjectName("tabs_")
		self.appearance_tab = QtWidgets.QWidget()
		self.appearance_tab.setObjectName("appearance_tab")
		self.themes_label = QtWidgets.QLabel(self.appearance_tab)
		self.themes_label.setGeometry(QtCore.QRect(10, 10, 511, 31))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(16)
		self.themes_label.setFont(font)
		self.themes_label.setObjectName("themes_label")
		self.light_btn = QtWidgets.QPushButton(self.appearance_tab)
		self.light_btn.setGeometry(QtCore.QRect(10, 60, 251, 151))
		self.light_btn.setStyleSheet("border: 2px solid rgb(82, 183, 255);\n"
"border-radius: 5px;\n"
"color: rgb(0, 0, 0);")
		self.light_btn.setText("")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("Bin/Icons/light_mode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.light_btn.setIcon(icon)
		self.light_btn.setIconSize(QtCore.QSize(150, 250))
		self.light_btn.setObjectName("light_btn")
		self.light_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.dark_btn = QtWidgets.QPushButton(self.appearance_tab)
		self.dark_btn.setGeometry(QtCore.QRect(270, 60, 251, 151))
		self.dark_btn.setStyleSheet("border: 2px solid rgb(82, 183, 255);\n"
"border-radius: 5px;\n"
"color: rgb(0, 0, 0);")
		self.dark_btn.setText("")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("Bin/Icons/dark_mode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.dark_btn.setIcon(icon1)
		self.dark_btn.setIconSize(QtCore.QSize(100, 100))
		self.dark_btn.setObjectName("dark_btn")
		self.dark_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.light_mode_label = QtWidgets.QLabel(self.appearance_tab)
		self.light_mode_label.setGeometry(QtCore.QRect(10, 220, 251, 21))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(10)
		self.light_mode_label.setFont(font)
		self.light_mode_label.setAlignment(QtCore.Qt.AlignCenter)
		self.light_mode_label.setObjectName("light_mode_label")
		self.dark_mode_label = QtWidgets.QLabel(self.appearance_tab)
		self.dark_mode_label.setGeometry(QtCore.QRect(270, 220, 251, 21))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(10)
		self.dark_mode_label.setFont(font)
		self.dark_mode_label.setAlignment(QtCore.Qt.AlignCenter)
		self.dark_mode_label.setObjectName("dark_mode_label")
		self.tabs_.addTab(self.appearance_tab, "")
		self.defaults_tab = QtWidgets.QWidget()
		self.defaults_tab.setObjectName("defaults_tab")
		self.save_btn = QtWidgets.QPushButton(self.defaults_tab)
		self.save_btn.setGeometry(QtCore.QRect(410, 310, 111, 31))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(12)
		self.save_btn.setFont(font)
		self.save_btn.setStyleSheet("border: 2px solid rgb(82, 183, 255);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(82, 183, 255);")
		self.save_btn.setObjectName("save_btn")
		self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.voice_label = QtWidgets.QLabel(self.defaults_tab)
		self.voice_label.setGeometry(QtCore.QRect(10, 10, 511, 31))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(16)
		self.voice_label.setFont(font)
		self.voice_label.setObjectName("voice_label")
		self.file_type_label = QtWidgets.QLabel(self.defaults_tab)
		self.file_type_label.setGeometry(QtCore.QRect(10, 110, 511, 31))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(16)
		self.file_type_label.setFont(font)
		self.file_type_label.setObjectName("file_type_label")
		self.quality_label = QtWidgets.QLabel(self.defaults_tab)
		self.quality_label.setGeometry(QtCore.QRect(10, 200, 511, 31))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(16)
		self.quality_label.setFont(font)
		self.quality_label.setObjectName("quality_label")
		self.voice_box = QtWidgets.QComboBox(self.defaults_tab)
		self.voice_box.setGeometry(QtCore.QRect(10, 60, 511, 31))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(12)
		self.voice_box.setFont(font)
		self.voice_box.setStyleSheet("border: 2px solid rgb(82, 183, 255);\n"
"")
		self.voice_box.setObjectName("voice_box")
		self.voice_box.addItem("")
		self.voice_box.addItem("")
		self.file_type_box = QtWidgets.QComboBox(self.defaults_tab)
		self.file_type_box.setGeometry(QtCore.QRect(10, 150, 511, 31))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(12)
		self.file_type_box.setFont(font)
		self.file_type_box.setStyleSheet("border: 2px solid rgb(82, 183, 255);\n"
"")
		self.file_type_box.setObjectName("file_type_box")
		self.file_type_box.addItem("")
		self.file_type_box.addItem("")
		self.file_type_box.addItem("")
		self.quality_box = QtWidgets.QComboBox(self.defaults_tab)
		self.quality_box.setGeometry(QtCore.QRect(10, 240, 511, 31))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(12)
		self.quality_box.setFont(font)
		self.quality_box.setStyleSheet("border: 2px solid rgb(82, 183, 255);\n"
"")
		self.quality_box.setObjectName("quality_box")
		self.quality_box.addItem("")
		self.quality_box.addItem("")
		self.quality_box.addItem("")
		self.tabs_.addTab(self.defaults_tab, "")
		self.feed_back = QtWidgets.QWidget()
		self.feed_back.setObjectName("feed_back")
		self.name_box = QtWidgets.QLineEdit(self.feed_back)
		self.name_box.setGeometry(QtCore.QRect(111, 120, 321, 31))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(12)
		self.name_box.setFont(font)
		self.name_box.setStyleSheet("border: 2px solid rgb(82, 183, 255);\n"
"border-radius: 5px;\n"
"color: rgb(0, 0, 0);")
		self.name_box.setObjectName("name_box")
		self.name_box.setFocusPolicy(QtCore.Qt.ClickFocus)
		self.message_box = QtWidgets.QTextEdit(self.feed_back)
		self.message_box.setGeometry(QtCore.QRect(111, 160, 321, 141))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(12)
		self.message_box.setFont(font)
		self.message_box.setStyleSheet("border: 2px solid rgb(82, 183, 255);\n"
"border-radius: 5px;\n"
"color: rgb(0, 0, 0);")
		self.message_box.setObjectName("message_box")
		self.message_box.setFocusPolicy(QtCore.Qt.ClickFocus)
		self.message_btn = QtWidgets.QPushButton(self.feed_back)
		self.message_btn.setGeometry(QtCore.QRect(320, 310, 111, 31))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(12)
		self.message_btn.setFont(font)
		self.message_btn.setStyleSheet("border: 2px solid rgb(82, 183, 255);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(82, 183, 255);")
		self.message_btn.setObjectName("message_btn")
		self.message_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.tabs_.addTab(self.feed_back, "")
		settings_window.setCentralWidget(self.centralwidget)

		self.retranslateUi(settings_window)
		self.tabs_.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(settings_window)

	def retranslateUi(self, settings_window):
		_translate = QtCore.QCoreApplication.translate
		settings_window.setWindowTitle(_translate("settings_window", "Settings"))
		self.themes_label.setText(_translate("settings_window", "Themes"))
		self.light_mode_label.setText(_translate("settings_window", "Light Mode"))
		self.dark_mode_label.setText(_translate("settings_window", "Dark Mode"))
		self.tabs_.setTabText(self.tabs_.indexOf(self.appearance_tab), _translate("settings_window", "Appearance"))
		self.voice_label.setText(_translate("settings_window", "Voice"))
		self.file_type_label.setText(_translate("settings_window", "File Type"))
		self.quality_label.setText(_translate("settings_window", "Quality"))
		self.voice_box.setItemText(0, _translate("settings_window", "Male Voice"))
		self.voice_box.setItemText(1, _translate("settings_window", "Female Voice"))
		self.file_type_box.setItemText(0, _translate("settings_window", "MP3"))
		self.file_type_box.setItemText(1, _translate("settings_window", "OGG"))
		self.file_type_box.setItemText(2, _translate("settings_window", "WAV"))
		self.quality_box.setItemText(0, _translate("settings_window", "Excellent Quality"))
		self.quality_box.setItemText(1, _translate("settings_window", "Medium Quality"))
		self.quality_box.setItemText(2, _translate("settings_window", "Normal Quality"))
		self.tabs_.setTabText(self.tabs_.indexOf(self.defaults_tab), _translate("settings_window", "Defaults"))
		self.name_box.setPlaceholderText(_translate("settings_window", "Your Name"))
		self.message_box.setPlaceholderText(_translate("settings_window", "Your Feedback Message"))
		self.message_btn.setText(_translate("settings_window", "Send"))
		self.save_btn.setText(_translate("settings_window", "Save"))
		self.tabs_.setTabText(self.tabs_.indexOf(self.feed_back), _translate("settings_window", "Feedback"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	settings_window = QtWidgets.QMainWindow()
	ui = Ui_settings_window()
	ui.setupUi(settings_window)
	settings_window.show()
	sys.exit(app.exec_())